<?php


class DivideByZeroException extends Exception
{
    public function __toString(): string
    {
//        parent::__toString(); // TODO: Change the autogenerated stub
        return "Cannot divide by Zero";
    }
}